trigger:
- main

pool:
  name: MSP

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

- script: dotnet restore Lab4_Library.sln
  displayName: Restore

- script: dotnet build Lab4_Library.sln --configuration Release
  displayName: Build

- script: dotnet pack Lab4_Library.sln --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: Pack

- task: NuGetAuthenticate@1

- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: internal
    publishVstsFeed: Lab4-Question1/stringextensions-feed
